// Builds src/geo.js: country outlines for each world-map region, already
// projected into map pixels, clipped to the region and simplified.
//
//   node tools/build-geo.mjs [path/to/ne_10m_admin_0_countries.geojson]
//
// Without a path it downloads Natural Earth's 1:10m countries (public domain).
import { readFile, writeFile } from 'node:fs/promises';
import { REGIONS, project, MAP_TOP, MAP_BOTTOM } from '../src/worldmap.js';

const SOURCE = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson';
const TOLERANCE = 0.45; // px: simplification error allowed
const MARGIN = 3; // px of overdraw kept around each region before canvas clipping

const load = async (path) => JSON.parse(path ? await readFile(path, 'utf8') : await (await fetch(SOURCE)).text());

/** Sutherland–Hodgman clip of a closed ring against an axis-aligned rectangle. */
function clipRing(ring, { x0, y0, x1, y1 }) {
  const edges = [
    [(p) => p[0] >= x0, (a, b) => [x0, a[1] + ((b[1] - a[1]) * (x0 - a[0])) / (b[0] - a[0])]],
    [(p) => p[0] <= x1, (a, b) => [x1, a[1] + ((b[1] - a[1]) * (x1 - a[0])) / (b[0] - a[0])]],
    [(p) => p[1] >= y0, (a, b) => [a[0] + ((b[0] - a[0]) * (y0 - a[1])) / (b[1] - a[1]), y0]],
    [(p) => p[1] <= y1, (a, b) => [a[0] + ((b[0] - a[0]) * (y1 - a[1])) / (b[1] - a[1]), y1]],
  ];
  let out = ring;
  for (const [inside, cross] of edges) {
    const input = out;
    out = [];
    for (let i = 0; i < input.length; i++) {
      const cur = input[i];
      const prev = input[(i + input.length - 1) % input.length];
      if (inside(cur)) {
        if (!inside(prev)) out.push(cross(prev, cur));
        out.push(cur);
      } else if (inside(prev)) {
        out.push(cross(prev, cur));
      }
    }
    if (!out.length) return [];
  }
  return out;
}

/** Douglas–Peucker simplification of an open polyline. */
function simplify(points, tol) {
  if (points.length < 3) return points;
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = points[a];
    const [bx, by] = points[b];
    const len = Math.hypot(bx - ax, by - ay) || 1;
    let worst = -1;
    let at = -1;
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs((bx - ax) * (ay - points[i][1]) - (ax - points[i][0]) * (by - ay)) / len;
      if (d > worst) {
        worst = d;
        at = i;
      }
    }
    if (worst > tol) {
      keep[at] = 1;
      stack.push([a, at], [at, b]);
    }
  }
  return points.filter((_, i) => keep[i]);
}

/** Closed rings start and end on the same point, so split at the farthest point and simplify both halves. */
function simplifyRing(ring, tol) {
  let far = 0;
  let best = -1;
  ring.forEach(([x, y], i) => {
    const d = Math.hypot(x - ring[0][0], y - ring[0][1]);
    if (d > best) {
      best = d;
      far = i;
    }
  });
  const first = simplify(ring.slice(0, far + 1), tol);
  const second = simplify([...ring.slice(far), ring[0]], tol);
  return [...first, ...second.slice(1, -1)];
}

const area = (ring) => Math.abs(ring.reduce((s, p, i) => {
  const q = ring[(i + 1) % ring.length];
  return s + p[0] * q[1] - q[0] * p[1];
}, 0)) / 2;

const polygonsOf = (geometry) => (geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates);

const world = await load(process.argv[2]);
const out = {};
for (const region of REGIONS) {
  const rect = { x0: region.x0 - MARGIN, x1: region.x1 + MARGIN, y0: MAP_TOP - MARGIN, y1: MAP_BOTTOM + MARGIN };
  const host = [];
  const others = [];
  for (const feature of world.features) {
    const code = feature.properties.ADM0_A3;
    for (const polygon of polygonsOf(feature.geometry)) {
      // Outer ring only: holes (lakes inside countries) are too small to matter at this scale.
      const ring = polygon[0].map(([lon, lat]) => {
        const p = project(region, lon, lat);
        return [p.x, p.y];
      });
      const clipped = clipRing(ring, rect);
      if (clipped.length < 3 || area(clipped) < 3) continue;
      const simple = simplifyRing(clipped, TOLERANCE);
      if (simple.length < 3) continue;
      const flat = simple.flatMap(([x, y]) => [Math.round(x * 10) / 10, Math.round(y * 10) / 10]);
      (code === region.host ? host : others).push(flat);
    }
  }
  out[region.theme] = { host, others };
  const points = [...host, ...others].reduce((n, r) => n + r.length / 2, 0);
  console.log(`${region.theme}: ${host.length} host rings, ${others.length} neighbour rings, ${points} points`);
}

const header = '// Generated by tools/build-geo.mjs from Natural Earth 1:10m countries (public domain).\n'
  + '// Country outlines per world-map region, in map pixels. Do not edit by hand.\n';
await writeFile(new URL('../src/geo.js', import.meta.url), `${header}export const GEO = ${JSON.stringify(out)};\n`);
